# ChatBubble 配置文件

# 气泡设置
bubble:
  # 气泡显示时间（秒）
  display-duration: 10
  # 气泡高度偏移（相对于玩家头顶）
  height-offset: 0.5
  # 气泡大小
  scale: 1.0
  # 是否启用动画效果
  enable-animation: true
  # 动画持续时间（秒）
  animation-duration: 0.5
  # 位置更新频率（tick，1tick=50ms，0=每tick更新，1=每2tick更新，2=每3tick更新）
  # 设置为0实现完全无延迟跟踪
  position-update-frequency: 0
  # 位置变化阈值（小于此值不更新位置，减少网络流量）
  # 设置为0.0001实现最精确的跟踪
  position-threshold: 0.0001

# 消息设置
messages:
  # 气泡显示的消息格式
  format: "&7[&f%player%&7] &f%message%"
  # 是否显示玩家名称
  show-player-name: true
  # 最大消息长度
  max-length: 50

# 权限设置
permissions:
  # 需要权限才能使用气泡
  require-permission: false
  # 权限节点
  permission-node: "chatbubble.use"

# 调试设置
debug:
  # 是否启用调试模式
  enabled: true
  # 调试日志级别
  log-level: "INFO"
